import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/navigation";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: {
    // 타입스크립트에서 작동
    // template: "%s | Next Study",
    // metadata가 없는 페이지는 default가 출력됨
    default: "Next Study"
  },
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
